### ISSUE TITLE
TearingEffect on ST7789

### ISSUE THREAD

**Issue by nishanthkarthik** [almindor/mipidsi#118]
Hi! I am a noob so please bear with me :)

Does setting `TearingEffect` make a difference when I write a bunch of pixels using `set_pixels`? I tried both `Vertical` and `HorizontalAndVertical` but I still see tearing when I alternate between black and white to fill the entire screen.

I am using ST7789 with a 135x240 display on ESP32. The tearing effect line mode number 1 (section 8.15.1 of ST7789VW datasheet) looks like what I want but I am not sure how to access this using the API.

**Comment by rfuest** [comment]
`set_tearing_effect` will only enable the tearing effect output on the controller and not change how `set_pixels` works. You will need to manually synchronize the display update with the tearing effect output (see section 8.15.3 and 8.15.4 in the datasheet). Unfortunately the tearing effect output isn't available on most cheap display modules.

**Comment by nishanthkarthik** [comment]
Thanks, makes sense. I'll close the issue since my display module probably doesn't support it.
