### ISSUE TITLE
Not compatible with display-interface-spi version 0.5.0

### ISSUE THREAD

**Issue by baget** [almindor/mipidsi#123]
Mipidsi is not compatible with display-interface-spi version 0.5.0

getting competition errors, even after moving to SPIInterface struct.

**Comment by rfuest** [comment]
The next release of `mipidsi` will be compatible with `display-interface` 0.5.0. If you need support now you have to use a GIT dependency. There probably won't be any more breaking code changes between now and the next stable release.

**Comment by almindor** [comment]
This should be solved now
