### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by KortanZ** [almindor/mipidsi#137]
I know we have #60 and #72 , but they all seems inactive for a relative long time. Will there be any plan to complete the async support?
 : )

**Comment by almindor** [comment]
Sorry for the big delay. Async is not on my radar, but if it's added compatible with 0.8 version I'll do a review and pull it in, provided whoever does it willing to join the project and maintain the async versions.

I'm closing the issue as part of issues cleanup but feel free to re-open if activity pertaining to it pops up.
