### ISSUE TITLE
Is the support available for esp32s3 gc9a01 board

### ISSUE THREAD

**Issue by MohaBeacon** [almindor/mipidsi#140]
tried building it with slint example - didn't work as expected.

https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-1.28

**Comment by rfuest** [comment]
You'll need to provide us with additional information, like:
- What didn't work exactly? Did the code not compile, did the display show nothing or did the display show a corrupted image?
- Did you check everything that is mentioned in https://github.com/almindor/mipidsi/blob/master/docs/TROUBLESHOOTING.md?
- Which version of mipidsi are you using?
- What code did you use to initialize the display?
- Does the problem also occur if you don't use slint, e.g. by drawing the test image that is included in the `mipidsi` crate:
  ```rust
  TestImage::new().draw(&mut display).unwrap();
  ```

**Comment by almindor** [comment]
Closing as inactive, please feel free to reopen.
