### ISSUE TITLE
Document changed default color order

### ISSUE THREAD

**Issue by rfuest** [almindor/mipidsi#47]
The default color order for some display was changed in #36, but this hasn't been documented in the changelog or the migration notes. 

This change will probably affect many users, so that it would also be a good idea to add a troubleshooting section for common color problems to the docs. Some example images and/or directions how to identify RGB/BGR or color inversion on TN vs IPS displays would be very useful IMO.

**Comment by almindor** [comment]
Hmm, I thought I kept it what the original inits were using. Did I miss something?

**Comment by almindor** [comment]
> You did remove the incorrect RGB/BGR inversion in this commit: [6a16384](https://github.com/almindor/mipidsi/commit/6a1638411d1f0536243bd21e34b4675346da5876)

Ah the 7789 yes. Must've been my display's setup matched it. I'll make it none are inverted by default in the next release.

**Comment by rfuest** [comment]
> Ah the 7789 yes. Must've been my display's setup matched it. I'll make it none are inverted by default in the next release.

The color inversion for the ST7789 in the `default_options` is actually part of #48 and not this issue. This issue was meant to discuss the inverted RGB/BGR bit in `MADCTL` for ST7735s and ILI9342C.

**Comment by almindor** [comment]
> > Ah the 7789 yes. Must've been my display's setup matched it. I'll make it none are inverted by default in the next release.
> 
> The color inversion for the ST7789 in the `default_options` is actually part of #48 and not this issue. This issue was meant to discuss the inverted RGB/BGR bit in `MADCTL` for ST7735s and ILI9342C.

Aah right. In either case I think the standard should be no-inversion for any of the "defaults" regardless of model, unless there's one that for some reason is always wire specific.

**Comment by almindor** [comment]
I believe this is fixed
