### ISSUE TITLE
Make DCS API more consistent

### ISSUE THREAD

**Issue by rfuest** [almindor/mipidsi#92]
While reviewing #91 I noticed that there is some inconsistency in the `dcs` module, which we might want to fix as a part of a future breaking change. `SetPixelFormat` uses a private tuple field and a `new` constructor, while other types with one parameter use a public tuple field and don't provide a constructor. IMO we should use a private fields and a constructor for all command types with parameters to be consistent.

**Comment by almindor** [comment]
I agree, but I'm quite busy atm. I can have a look later. Happy to review a PR though.

This should preferably be addressed before e-h 1.0 support so we can have it all in one breaking change.
